# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trustlist',
        ),
    ]
