# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_delete_trustlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlist',
            name='key',
            field=models.IntegerField(default='0', max_length=20),
        ),
    ]
